init:
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE

test_script:
- sh: appveyor PushArtifact .profile
- ps: Push-AppveyorArtifact .profile
- sh: pwsh Push-AppveyorArtifact .profile

build: off
