init:
- appveyor version
- ps: $env:APPVEYOR_BUILD_WORKER_CLOUD
- ps: $env:APPVEYOR_BUILD_WORKER_IMAGE
- sh: cat $HOME/.config/powershell/Microsoft.PowerShell_profile.ps1

build_script:
- echo "this is a test artifact file" >artifact
- echo "this is a test artifact file" >.artifact

test_script:
- appveyor PushArtifact artifact
- ps: Push-AppveyorArtifact artifact
- sh: pwsh -c 'Push-AppveyorArtifact artifact'

# check different paths
- ps: Push-AppveyorArtifact .artifact
- ps: Push-AppveyorArtifact ./artifact
- ps: Push-AppveyorArtifact $env:APPVEYOR_BUILD_FOLDER/artifact

- appveyor AddMessage "Message 1" -Category Information
- ps: Add-AppveyorMessage -Message "Message 2" -Category Information
- sh: pwsh -c 'Add-AppveyorMessage -Message "Message 3" -Category Information'

- appveyor AddCompilationMessage "Compilation Message 1" -Category Information -Line 1 -Column 2
- ps: Add-AppveyorCompilationMessage -Message "Compilation Message 2" -Category Information -Line 1 -Column 2
- sh: pwsh -c 'Add-AppveyorCompilationMessage -Message "Compilation Message 3" -Category Information -Line 1 -Column 2'

- appveyor SetVariable -Name 'MyVar1' -Value 'This is a test message'
- ps: Set-AppveyorBuildVariable 'MyVar2' 'This is a test message'
- sh: pwsh -c "Set-AppveyorBuildVariable 'MyVar3' 'This is a test message'"

- appveyor AddTest -Name "Test A" -Framework NUnit -Filename a.exe
- ps: Add-AppveyorTest -Name "Test B" -Framework NUnit -Filename b.exe
- sh: pwsh -c 'Add-AppveyorTest -Name "Test C" -Framework NUnit -Filename c.exe'

- appveyor UpdateTest -Name "Test A" -Framework NUnit -Outcome Passed -FileName a.exe -Duration 123 
- ps: Update-AppveyorTest -Name "Test B" -Framework NUnit -Outcome Passed -FileName b.exe -Duration 234
- sh: pwsh -c 'Update-AppveyorTest -Name "TestC" -Framework NUnit -Outcome Passed -FileName c.exe -Duration 345'

- appveyor UpdateBuild -Message "Build Message 1"
- ps: Update-AppveyorBuild -Message "Build Message 2"
- sh: pwsh -c 'Update-AppveyorBuild -Message "Build Message 3"'

- ps: |
    $headers = @{
      "Content-type" = "application/json"
    }
    $body = @{
        testName="Test from PowerShell"
        testFramework="NUnit"
        fileName="tests.dll"
        outcome="Passed"
        durationMilliseconds="1200"
        ErrorMessage=""
        ErrorStackTrace=""
        StdOut=""
        StdErr=""
    }
    $body = $body | ConvertTo-Json
    Invoke-RestMethod -Uri "$($env:APPVEYOR_API_URL)api/tests" -Headers $headers  -Body $body -Method POST
